// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8U8Xj7lYnOvvVZC_XHJVBWExDtgY-E-c',
    appId: '1:465503566707:web:09747a4d9823b1adf72306',
    messagingSenderId: '465503566707',
    projectId: 'fir-flutter-codelab-c1dda',
    authDomain: 'fir-flutter-codelab-c1dda.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-c1dda.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMXJE6RplwZe32xCmoxrro1jRgzwaxBeM',
    appId: '1:465503566707:android:b77dc02a5610bb47f72306',
    messagingSenderId: '465503566707',
    projectId: 'fir-flutter-codelab-c1dda',
    storageBucket: 'fir-flutter-codelab-c1dda.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNtsqPDyBDK-cblAWJUbthzqADF8P48os',
    appId: '1:465503566707:ios:a14ad996a96a72cdf72306',
    messagingSenderId: '465503566707',
    projectId: 'fir-flutter-codelab-c1dda',
    storageBucket: 'fir-flutter-codelab-c1dda.firebasestorage.app',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNtsqPDyBDK-cblAWJUbthzqADF8P48os',
    appId: '1:465503566707:ios:a14ad996a96a72cdf72306',
    messagingSenderId: '465503566707',
    projectId: 'fir-flutter-codelab-c1dda',
    storageBucket: 'fir-flutter-codelab-c1dda.firebasestorage.app',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8U8Xj7lYnOvvVZC_XHJVBWExDtgY-E-c',
    appId: '1:465503566707:web:c81e0acbf756a835f72306',
    messagingSenderId: '465503566707',
    projectId: 'fir-flutter-codelab-c1dda',
    authDomain: 'fir-flutter-codelab-c1dda.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-c1dda.firebasestorage.app',
  );
}
